//
// Code auto-generated by initpackage (XSPEC12 local model package 
// code generator).  Do not edit
// Package: neipkg Created :
// Initializer: neipkg.cxx

#include <XSUser/UserInterface/xstcl.h>

#include  "neipkgFunctionMap.h"
#include  <XSModelFunction.h>

extern "C" int Neipkg_Init(Tcl_Interp* tclInterp);
extern "C" int Neipkg_SafeInit(Tcl_Interp* tclInterp);

int Neipkg_Init(Tcl_Interp* tclInterp)
{
        return Neipkg_SafeInit(tclInterp);
}

int Neipkg_SafeInit(Tcl_Interp* tclInterp)
{

        char PACKAGE[] = "neipkg";
        char VERSION[] = "1.0";
        Tcl_PkgProvide(tclInterp, PACKAGE, VERSION);
        createneipkgFunctionMap();
        XSModelFunction::updateComponentList
              ("/Users/atran3/snr-research/code/srcutlog/lmodel.dat");
        return TCL_OK;

}

