//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: neipkg
// Function header: neipkgFunctionMap.h

#ifndef    FUNCTIONMAP_H
#define    FUNCTIONMAP_H

#include    <funcType.h>

class    XSModelFunction;

extern    ModelFunctionMap  XSFunctionMap;

void  createneipkgFunctionMap();

extern "C"  {


	xsf77Call    srcutlog_;
}


#endif
