//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: neipkg
// Function body: neipkgFunctionMap.cxx

#include    "neipkgFunctionMap.h"

#include    <XSModelFunction.h>

void 
createneipkgFunctionMap()
{


	XSFunctionMap["srcutlog"] = new XSCall<xsf77Call>(srcutlog_);

}
